In [11]:
import polars as pl
import os 
from pathlib import Path

In [23]:
ROOT_DIR = "./DATA"

path=f"{ROOT_DIR}/complete_dataset.parquet"

In [24]:
df=pl.read_parquet(path)
df.head()

shape: (5, 68)
┌────────────┬───────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ company_na ┆ siren     ┆ nic  ┆ legal_form ┆ … ┆ city_ref   ┆ department ┆ lat_ref   ┆ lon_ref   │
│ me         ┆ ---       ┆ ---  ┆ ---        ┆   ┆ ---        ┆ _ref       ┆ ---       ┆ ---       │
│ ---        ┆ str       ┆ str  ┆ str        ┆   ┆ str        ┆ ---        ┆ str       ┆ str       │
│ str        ┆           ┆      ┆            ┆   ┆            ┆ str        ┆           ┆           │
╞════════════╪═══════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
└────────────┴───────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [25]:
df.null_count()

shape: (1, 68)
┌──────────────┬───────┬────────┬────────────┬───┬──────────┬────────────────┬─────────┬─────────┐
│ company_name ┆ siren ┆ nic    ┆ legal_form ┆ … ┆ city_ref ┆ department_ref ┆ lat_ref ┆ lon_ref │
│ ---          ┆ ---   ┆ ---    ┆ ---        ┆   ┆ ---      ┆ ---            ┆ ---     ┆ ---     │
│ u32          ┆ u32   ┆ u32    ┆ u32        ┆   ┆ u32      ┆ u32            ┆ u32     ┆ u32     │
╞══════════════╪═══════╪════════╪════════════╪═══╪══════════╪════════════════╪═════════╪═════════╡
│ 0            ┆ 0     ┆ 167038 ┆ 162299     ┆ … ┆ 7289     ┆ 363185         ┆ 7926    ┆ 7926    │
└──────────────┴───────┴────────┴────────────┴───┴──────────┴────────────────┴─────────┴─────────┘

In [ ]:
df = df.unique(subset=["siren"], keep="first", maintain_order=True)

df = df.with_columns(
    [
        pl.col("company_name").fill_null("Inconnu"),
        pl.col("industry_code").fill_null("UNKNOWN"),
        pl.col("industry_description").fill_null("Inconnu"),
        pl.col("industry_group_65").fill_null("Inconnu"),
        pl.col("industry_sector_40").fill_null("Inconnu"),
        pl.col("address").fill_null(""),
        pl.col("city").fill_null(""),
        pl.col("postal_code").fill_null(""),
        pl.col("website").fill_null(""),
        pl.col("phone").fill_null(""),
        pl.col("email").fill_null(""),
    ]
)

df

shape: (390_616, 68)
┌────────────┬───────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ company_na ┆ siren     ┆ nic   ┆ legal_form ┆ … ┆ city_ref   ┆ departmen ┆ lat_ref   ┆ lon_ref   │
│ me         ┆ ---       ┆ ---   ┆ ---        ┆   ┆ ---        ┆ t_ref     ┆ ---       ┆ ---       │
│ ---        ┆ str       ┆ str   ┆ str        ┆   ┆ str        ┆ ---       ┆ str       ┆ str       │
│ str        ┆           ┆       ┆            ┆   ┆            ┆ str       ┆           ┆           │
╞════════════╪═══════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ BETREC IG  ┆ 065502395 ┆ null  ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null      ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆       ┆            ┆   ┆ CLARAFOND  ┆           ┆ 9398787   ┆ 06027523  │
│ SNEF       ┆ 056800659 ┆ null  ┆ null       ┆ … ┆ COLOMBES   ┆ 92        ┆ 48.921824 ┆ 2.2468590 │
│            ┆           ┆       ┆            ┆   ┆            ┆           ┆ 961438986 ┆ 110649505 │
│ CUNY ELECT ┆ 026120063 ┆ null  ┆ null       ┆ … ┆ AUBIAC     ┆ null      ┆ 44.137840 ┆ 0.5687273 │
│ RICITE     ┆           ┆       ┆            ┆   ┆            ┆           ┆ 970011    ┆ 39995875  │
│ F.AUGIER   ┆ 058808460 ┆ 00040 ┆ Société à  ┆ … ┆ TRETS      ┆ null      ┆ 43.445231 ┆ 5.7137338 │
│ ET CIE     ┆           ┆       ┆ responsabi ┆   ┆            ┆           ┆ 67057564  ┆ 648175895 │
│            ┆           ┆       ┆ lité       ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ limit…     ┆   ┆            ┆           ┆           ┆           │
│ LM RENOV   ┆ 100649094 ┆ null  ┆ null       ┆ … ┆ PARIS 11   ┆ 75        ┆ 48.860073 ┆ 2.3815596 │
│ FRANCE     ┆           ┆       ┆            ┆   ┆            ┆           ┆ 17753911  ┆ 509625725 │
│ …          ┆ …         ┆ …     ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ HRBT       ┆ 992478206 ┆ 00012 ┆ Société    ┆ … ┆ DIJON      ┆ null      ┆ 47.331869 ┆ 5.0322190 │
│            ┆           ┆       ┆ par        ┆   ┆            ┆           ┆ 72578652  ┆ 99706737  │
│            ┆           ┆       ┆ actions    ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ simplifiée ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ …          ┆   ┆            ┆           ┆           ┆           │
│ SM ELEC    ┆ 945133833 ┆ 00018 ┆ Société    ┆ … ┆ GRENOBLE   ┆ null      ┆ 45.184233 ┆ 5.7155400 │
│            ┆           ┆       ┆ par        ┆   ┆            ┆           ┆ 4633299   ┆ 18884406  │
│            ┆           ┆       ┆ actions    ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ simplifiée ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ …          ┆   ┆            ┆           ┆           ┆           │
│ StructiBTP ┆ 945066306 ┆ 00016 ┆ Société    ┆ … ┆ REIMS      ┆ null      ┆ 49.253540 ┆ 4.0551079 │
│            ┆           ┆       ┆ par        ┆   ┆            ┆           ┆ 57262456  ┆ 757832245 │
│            ┆           ┆       ┆ actions    ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ simplifiée ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ …          ┆   ┆            ┆           ┆           ┆           │
│ FIT IMMO   ┆ 944492818 ┆ 00017 ┆ Société    ┆ … ┆ PARIS 16   ┆ 75        ┆ 48.857155 ┆ 2.2629781 │
│            ┆           ┆       ┆ par        ┆   ┆            ┆           ┆ 31831008  ┆ 9673204   │
│            ┆           ┆       ┆ actions    ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ simplifiée ┆   ┆            ┆           ┆           ┆           │
│ AMT        ┆ 988982112 ┆ 00019 ┆ Société à  ┆ … ┆ BARATIER   ┆ null      ┆ 44.505074 ┆ 6.5040244 │
│            ┆           ┆       ┆ responsabi ┆   ┆            ┆           ┆ 13267944  ┆ 88047623  │
│            ┆           ┆       ┆ lité       ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ limit…     ┆   ┆            ┆           ┆           ┆           │
└────────────┴───────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [15]:
df

shape: (497_145, 68)
┌────────────┬───────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ company_na ┆ siren     ┆ nic   ┆ legal_form ┆ … ┆ city_ref   ┆ departmen ┆ lat_ref   ┆ lon_ref   │
│ me         ┆ ---       ┆ ---   ┆ ---        ┆   ┆ ---        ┆ t_ref     ┆ ---       ┆ ---       │
│ ---        ┆ str       ┆ str   ┆ str        ┆   ┆ str        ┆ ---       ┆ str       ┆ str       │
│ str        ┆           ┆       ┆            ┆   ┆            ┆ str       ┆           ┆           │
╞════════════╪═══════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ BETREC IG  ┆ 065502395 ┆ null  ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null      ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆       ┆            ┆   ┆ CLARAFOND  ┆           ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null  ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null      ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆       ┆            ┆   ┆ CLARAFOND  ┆           ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null  ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null      ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆       ┆            ┆   ┆ CLARAFOND  ┆           ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null  ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null      ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆       ┆            ┆   ┆ CLARAFOND  ┆           ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null  ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null      ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆       ┆            ┆   ┆ CLARAFOND  ┆           ┆ 9398787   ┆ 06027523  │
│ …          ┆ …         ┆ …     ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ HRBT       ┆ 992478206 ┆ 00012 ┆ Société    ┆ … ┆ DIJON      ┆ null      ┆ 47.331869 ┆ 5.0322190 │
│            ┆           ┆       ┆ par        ┆   ┆            ┆           ┆ 72578652  ┆ 99706737  │
│            ┆           ┆       ┆ actions    ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ simplifiée ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ …          ┆   ┆            ┆           ┆           ┆           │
│ SM ELEC    ┆ 945133833 ┆ 00018 ┆ Société    ┆ … ┆ GRENOBLE   ┆ null      ┆ 45.184233 ┆ 5.7155400 │
│            ┆           ┆       ┆ par        ┆   ┆            ┆           ┆ 4633299   ┆ 18884406  │
│            ┆           ┆       ┆ actions    ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ simplifiée ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ …          ┆   ┆            ┆           ┆           ┆           │
│ StructiBTP ┆ 945066306 ┆ 00016 ┆ Société    ┆ … ┆ REIMS      ┆ null      ┆ 49.253540 ┆ 4.0551079 │
│            ┆           ┆       ┆ par        ┆   ┆            ┆           ┆ 57262456  ┆ 757832245 │
│            ┆           ┆       ┆ actions    ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ simplifiée ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ …          ┆   ┆            ┆           ┆           ┆           │
│ FIT IMMO   ┆ 944492818 ┆ 00017 ┆ Société    ┆ … ┆ PARIS 16   ┆ 75        ┆ 48.857155 ┆ 2.2629781 │
│            ┆           ┆       ┆ par        ┆   ┆            ┆           ┆ 31831008  ┆ 9673204   │
│            ┆           ┆       ┆ actions    ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ simplifiée ┆   ┆            ┆           ┆           ┆           │
│ AMT        ┆ 988982112 ┆ 00019 ┆ Société à  ┆ … ┆ BARATIER   ┆ null      ┆ 44.505074 ┆ 6.5040244 │
│            ┆           ┆       ┆ responsabi ┆   ┆            ┆           ┆ 13267944  ┆ 88047623  │
│            ┆           ┆       ┆ lité       ┆   ┆            ┆           ┆           ┆           │
│            ┆           ┆       ┆ limit…     ┆   ┆            ┆           ┆           ┆           │
└────────────┴───────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [16]:
for file in os.listdir(ROOT_DIR):
   
    CURRENT_PATH = Path(f"{ROOT_DIR}/{file}")
    if CURRENT_PATH.suffix != ".parquet":
        continue
    df=pl.read_parquet(CURRENT_PATH,n_rows=1)
    print(f"File: {file}")
    print(df.columns)
    print(len(df.columns))
    print("\n")

File: complete_dataset.parquet
['company_name', 'siren', 'nic', 'legal_form', 'industry_code', 'activity_sector', 'address', 'postal_code', 'city', 'department_code', 'department_name', 'region', 'registration_date', 'radiation_date', 'status', 'geolocation', 'siret', 'rge_company_name', 'rge_address', 'rge_postal_code', 'rge_city', 'rge_latitude', 'rge_longitude', 'rge_phone', 'rge_email', 'rge_website', 'rge_code_qualification', 'rge_name_qualification', 'rge_url_qualification', 'rge_certificate_name', 'rge_domain', 'rge_meta_domain', 'rge_organism', 'rge_particulier', 'rge_start_date', 'rge_end_date', 'stock_siren', 'stock_industry_code', 'stock_staff_size', 'stock_postal_code', 'stock_city', 'stock_address', 'stock_x_lambert_93', 'stock_y_lambert_93', 'stock_company_name', 'stock_company_type', 'stock_creation_date', 'pros_company_name', 'pros_industry_code', 'pros_staff_size', 'pros_company_type', 'pros_address', 'pros_city', 'pros_postal_code', 'pros_creation_date', 'pros_x_lambert_93', 'pros_y_lambert_93', 'staff_size_range', 'company_type', 'x_lambert_93', 'y_lambert_93', 'industry_description', 'industry_group_65', 'industry_sector_40', 'city_ref', 'department_ref', 'lat_ref', 'lon_ref']
68


File: prospecting_leads_2026.parquet
['siret', 'company_name', 'activitePrincipaleEtablissement', 'trancheEffectifsEtablissement', 'categorieEntreprise', 'address', 'libelleCommuneEtablissement', 'codePostalEtablissement', 'dateCreationUniteLegale', 'coordonneeLambertAbscisseEtablissement', 'coordonneeLambertOrdonneeEtablissement']
11


File: StockEtablissement_utf8.parquet
['siren', 'nic', 'siret', 'statutDiffusionEtablissement', 'dateCreationEtablissement', 'trancheEffectifsEtablissement', 'anneeEffectifsEtablissement', 'activitePrincipaleRegistreMetiersEtablissement', 'dateDernierTraitementEtablissement', 'etablissementSiege', 'nombrePeriodesEtablissement', 'complementAdresseEtablissement', 'numeroVoieEtablissement', 'indiceRepetitionEtablissement', 'dernierNumeroVoieEtablissement', 'indiceRepetitionDernierNumeroVoieEtablissement', 'typeVoieEtablissement', 'libelleVoieEtablissement', 'codePostalEtablissement', 'libelleCommuneEtablissement', 'libelleCommuneEtrangerEtablissement', 'distributionSpecialeEtablissement', 'codeCommuneEtablissement', 'codeCedexEtablissement', 'libelleCedexEtablissement', 'codePaysEtrangerEtablissement', 'libellePaysEtrangerEtablissement', 'identifiantAdresseEtablissement', 'coordonneeLambertAbscisseEtablissement', 'coordonneeLambertOrdonneeEtablissement', 'complementAdresse2Etablissement', 'numeroVoie2Etablissement', 'indiceRepetition2Etablissement', 'typeVoie2Etablissement', 'libelleVoie2Etablissement', 'codePostal2Etablissement', 'libelleCommune2Etablissement', 'libelleCommuneEtranger2Etablissement', 'distributionSpeciale2Etablissement', 'codeCommune2Etablissement', 'codeCedex2Etablissement', 'libelleCedex2Etablissement', 'codePaysEtranger2Etablissement', 'libellePaysEtranger2Etablissement', 'dateDebut', 'etatAdministratifEtablissement', 'enseigne1Etablissement', 'enseigne2Etablissement', 'enseigne3Etablissement', 'denominationUsuelleEtablissement', 'activitePrincipaleEtablissement', 'nomenclatureActivitePrincipaleEtablissement', 'caractereEmployeurEtablissement', 'activitePrincipaleNAF25Etablissement']
54


File: StockUniteLegale_utf8.parquet
['siren', 'statutDiffusionUniteLegale', 'unitePurgeeUniteLegale', 'dateCreationUniteLegale', 'sigleUniteLegale', 'sexeUniteLegale', 'prenom1UniteLegale', 'prenom2UniteLegale', 'prenom3UniteLegale', 'prenom4UniteLegale', 'prenomUsuelUniteLegale', 'pseudonymeUniteLegale', 'identifiantAssociationUniteLegale', 'trancheEffectifsUniteLegale', 'anneeEffectifsUniteLegale', 'dateDernierTraitementUniteLegale', 'nombrePeriodesUniteLegale', 'categorieEntreprise', 'anneeCategorieEntreprise', 'dateDebut', 'etatAdministratifUniteLegale', 'nomUniteLegale', 'nomUsageUniteLegale', 'denominationUniteLegale', 'denominationUsuelle1UniteLegale', 'denominationUsuelle2UniteLegale', 'denominationUsuelle3UniteLegale', 'categorieJuridiqueUniteLegale', 'activitePrincipaleUniteLegale', 'nomenclatureActivitePrincipaleUniteLegale', 'nicSiegeUniteLegale', 'economieSocialeSolidaireUniteLegale', 'societeMissionUniteLegale', 'caractereEmployeurUniteLegale', 'activitePrincipaleNAF25UniteLegale']
35

In [17]:
df = pl.read_parquet(path, n_rows=5)

In [18]:
df.head()

shape: (5, 68)
┌────────────┬───────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ company_na ┆ siren     ┆ nic  ┆ legal_form ┆ … ┆ city_ref   ┆ department ┆ lat_ref   ┆ lon_ref   │
│ me         ┆ ---       ┆ ---  ┆ ---        ┆   ┆ ---        ┆ _ref       ┆ ---       ┆ ---       │
│ ---        ┆ str       ┆ str  ┆ str        ┆   ┆ str        ┆ ---        ┆ str       ┆ str       │
│ str        ┆           ┆      ┆            ┆   ┆            ┆ str        ┆           ┆           │
╞════════════╪═══════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
│ BETREC IG  ┆ 065502395 ┆ null ┆ null       ┆ … ┆ DRUMETTAZ  ┆ null       ┆ 45.661009 ┆ 5.9376706 │
│ - SAVOIE   ┆           ┆      ┆            ┆   ┆ CLARAFOND  ┆            ┆ 9398787   ┆ 06027523  │
└────────────┴───────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [19]:
import polars as pl
import os

# Optimized for 2026 hardware: Uses all CPU cores and Streaming API
os.environ["POLARS_MAX_THREADS"] = str(os.cpu_count())

def build_prospecting_database(etab_path, unite_path, output_path):
    """
    Optimized pipeline to merge 30M+ rows into a clean prospecting dataset.
    Uses Lazy API for query optimization and Streaming for memory safety.
    """
    
    # 1. Setup Lazy Scanners
    etab_scan = pl.scan_parquet(etab_path)
    unite_scan = pl.scan_parquet(unite_path)

    # 2. Filter Legal Units (Parent Data)
    # Target: Active companies that allow commercial diffusion
    unite_filtered = unite_scan.filter(
        (pl.col("statutDiffusionUniteLegale") == "O") & 
        (pl.col("etatAdministratifUniteLegale") == "A")
    ).select([
        "siren",
        "denominationUniteLegale",
        "nomUniteLegale",
        "prenom1UniteLegale",
        "categorieEntreprise",
        "dateCreationUniteLegale"
    ])

    # 3. Filter Establishments (Local Data)
    # Target: Active locations with employee counts
    etab_filtered = etab_scan.filter(
        (pl.col("statutDiffusionEtablissement") == "O") & 
        (pl.col("etatAdministratifEtablissement") == "A")
    ).select([
        "siren",
        "siret",
        "enseigne1Etablissement",
        "activitePrincipaleEtablissement",
        "trancheEffectifsEtablissement",
        "codePostalEtablissement",
        "libelleCommuneEtablissement",
        "numeroVoieEtablissement",
        "typeVoieEtablissement",
        "libelleVoieEtablissement",
        "coordonneeLambertAbscisseEtablissement",
        "coordonneeLambertOrdonneeEtablissement"
    ])

    # 4. Join and Feature Engineering
    # Parallel processing across all cores
    prospecting_pipeline = (
        etab_filtered.join(unite_filtered, on="siren", how="inner")
        .with_columns([
            # Priority: Company Name > Sign > Person Name
            pl.coalesce([
                pl.col("denominationUniteLegale"),
                pl.col("enseigne1Etablissement"),
                pl.format("{} {}", pl.col("prenom1UniteLegale"), pl.col("nomUniteLegale"))
            ]).alias("company_name"),
            
            # Clean unified address
            pl.format("{} {} {} {} {}", 
                pl.col("numeroVoieEtablissement").fill_null(""),
                pl.col("typeVoieEtablissement").fill_null(""),
                pl.col("libelleVoieEtablissement").fill_null(""),
                pl.col("codePostalEtablissement").fill_null(""),
                pl.col("libelleCommuneEtablissement").fill_null("")
            ).str.replace_all(r"\s+", " ").str.strip_chars().alias("address")
        ])
        .select([
            "siret",
            "company_name",
            "activitePrincipaleEtablissement",
            "trancheEffectifsEtablissement",
            "categorieEntreprise",
            "address",
            "libelleCommuneEtablissement",
            "codePostalEtablissement",
            "dateCreationUniteLegale",
            "coordonneeLambertAbscisseEtablissement",
            "coordonneeLambertOrdonneeEtablissement"
        ])
    )

    # 5. Execute via Streaming
    # Writes results to disk batch-by-batch to prevent RAM exhaustion
    print("Executing optimized multi-threaded merge...")
    prospecting_pipeline.sink_parquet(output_path)
    print(f"Extraction complete: {output_path}")

In [20]:
if(os.path.exists("./DATA/prospecting_leads_2026.parquet")):
    print("Prospecting database already exists. Skipping extraction.")
else:
    build_prospecting_database(
            etab_path="./DATA/StockEtablissement_utf8.parquet",
            unite_path="./DATA/StockUniteLegale_utf8.parquet",
            output_path="./DATA/prospecting_leads_2026.parquet"
        )

Prospecting database already exists. Skipping extraction.

In [21]:
DF8 = pl.read_parquet("./DATA/prospecting_leads_2026.parquet")

In [22]:
DF8.unique().count()

KeyboardInterrupt:

In [ ]:
# Add this step to your pipeline to rename columns to meaningful English names
prospecting_pipeline = DF8.rename({
    "activitePrincipaleEtablissement": "industry_code",
    "trancheEffectifsEtablissement": "staff_size_range",
    "categorieEntreprise": "company_type",
    "libelleCommuneEtablissement": "city",
    "codePostalEtablissement": "zip_code",
    "dateCreationUniteLegale": "creation_date",
    "coordonneeLambertAbscisseEtablissement": "x_lambert_93",
    "coordonneeLambertOrdonneeEtablissement": "y_lambert_93"
})

In [ ]:
DF8 = (
    DF8
    .select([
        "siret",
        "company_name",
        "activitePrincipaleEtablissement",
        "trancheEffectifsEtablissement",
        "categorieEntreprise",
        "address",
        "libelleCommuneEtablissement",
        "codePostalEtablissement",
        "dateCreationUniteLegale",
        "coordonneeLambertAbscisseEtablissement",
        "coordonneeLambertOrdonneeEtablissement"
    ])
    .rename({
        "activitePrincipaleEtablissement": "industry_code",
        "trancheEffectifsEtablissement": "staff_size_range",
        "categorieEntreprise": "company_type",
        "libelleCommuneEtablissement": "city",
        "codePostalEtablissement": "zip_code",
        "dateCreationUniteLegale": "creation_date",
        "coordonneeLambertAbscisseEtablissement": "x_lambert_93",
        "coordonneeLambertOrdonneeEtablissement": "y_lambert_93"
    })
)

In [ ]:
DF8.head()

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ siret     ┆ company_n ┆ industry_ ┆ staff_siz ┆ … ┆ zip_code ┆ creation_ ┆ x_lambert ┆ y_lambert │
│ ---       ┆ ame       ┆ code      ┆ e_range   ┆   ┆ ---      ┆ date      ┆ _93       ┆ _93       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ str       ┆ str       ┆   ┆          ┆ date      ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 298600586 ┆ ASSOCIATI ┆ 42.99Z    ┆ NN        ┆ … ┆ 86190    ┆ 1961-06-2 ┆ 477574.57 ┆ 6623602.8 │
│ 00010     ┆ ON        ┆           ┆           ┆   ┆          ┆ 0         ┆ 88544328  ┆ 35517963  │
│           ┆ FONCIERE  ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ DE MAILLE ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 298600602 ┆ ASS       ┆ 42.99Z    ┆ NN        ┆ … ┆ 86330    ┆ 1963-01-2 ┆ null      ┆ null      │
│ 00015     ┆ FONCIERE  ┆           ┆           ┆   ┆          ┆ 1         ┆           ┆           │
│           ┆ DE REMEMB ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ REMENT D… ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 298600644 ┆ ASS       ┆ 42.99Z    ┆ NN        ┆ … ┆ 86110    ┆ 1964-07-0 ┆ null      ┆ null      │
│ 00017     ┆ FONCIERE  ┆           ┆           ┆   ┆          ┆ 6         ┆           ┆           │
│           ┆ DE REMEMB ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ DE MAZE…  ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 298600834 ┆ ASSOCIATI ┆ 42.99Z    ┆ NN        ┆ … ┆ 86120    ┆ 1969-01-0 ┆ 476678.29 ┆ 6673572.1 │
│ 00014     ┆ ON        ┆           ┆           ┆   ┆          ┆ 3         ┆ 80433072  ┆ 07521303  │
│           ┆ FONCIERE  ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ DE ROIFFE ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 298600842 ┆ ASS       ┆ 42.99Z    ┆ NN        ┆ … ┆ 86330    ┆ 1967-06-0 ┆ null      ┆ null      │
│ 00017     ┆ FONCIERE  ┆           ┆           ┆   ┆          ┆ 6         ┆           ┆           │
│           ┆ DE REMEMB ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ REMENT D… ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [ ]:
naf_mapping = pl.read_csv("./DATA/nomenclature-dactivites-francaise-naf-rev-2-code-ape.csv", separator=";").select([
    pl.col("code_naf").alias("industry_code"),
    pl.col("intitule_naf").alias("industry_description"),    
    pl.col("intitule_naf_65").alias("industry_group_65"),    
    pl.col("intitule_naf_40").alias("industry_sector_40") 
])

In [ ]:
naf_mapping.head(5)

shape: (5, 4)
┌───────────────┬───────────────────────────┬───────────────────────────┬──────────────────────────┐
│ industry_code ┆ industry_description      ┆ industry_group_65         ┆ industry_sector_40       │
│ ---           ┆ ---                       ┆ ---                       ┆ ---                      │
│ str           ┆ str                       ┆ str                       ┆ str                      │
╞═══════════════╪═══════════════════════════╪═══════════════════════════╪══════════════════════════╡
│ 3011          ┆ Construction de navires   ┆ Construction de navires   ┆ Construct. navires &     │
│               ┆ et de …                   ┆ et de …                   ┆ structure…               │
│ 4752A         ┆ Commerce de détail de     ┆ Comm. détail de           ┆ Com. dét. quinc. pein.   │
│               ┆ quincail…                 ┆ quincaillerie,…           ┆ etc. (m…                 │
│ 1629Z         ┆ Fabrication d'objets      ┆ Fabrication objets divers ┆ Fab. objet div. bois,    │
│               ┆ divers en…                ┆ en b…                     ┆ liège, v…                │
│ 6492Z         ┆ Autre distribution de     ┆ Autre distribution de     ┆ Autre distribution de    │
│               ┆ crédit                    ┆ crédit                    ┆ crédit                   │
│ 8899          ┆ Autre action sociale sans ┆ Autre action sociale sans ┆ Autre action sociale     │
│               ┆ hébe…                     ┆ hébe…                     ┆ sans hébr…               │
└───────────────┴───────────────────────────┴───────────────────────────┴──────────────────────────┘

In [ ]:
DF8=DF8.with_columns(
   pl.col("industry_code").str.replace(".", "", literal=True    )
)

In [ ]:
df = DF8.join(
    naf_mapping,
    on="industry_code",
    how="left"
)
df.head()

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siret     ┆ company_n ┆ industry_ ┆ staff_siz ┆ … ┆ y_lambert ┆ industry_ ┆ industry_ ┆ industry │
│ ---       ┆ ame       ┆ code      ┆ e_range   ┆   ┆ _93       ┆ descripti ┆ group_65  ┆ _sector_ │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ on        ┆ ---       ┆ 40       │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 298600586 ┆ ASSOCIATI ┆ 4299Z     ┆ NN        ┆ … ┆ 6623602.8 ┆ Construct ┆ Construct ┆ Constr.  │
│ 00010     ┆ ON        ┆           ┆           ┆   ┆ 35517963  ┆ ion       ┆ ion       ┆ aut.     │
│           ┆ FONCIERE  ┆           ┆           ┆   ┆           ┆ d'autres  ┆ d'autres  ┆ ouvrage  │
│           ┆ DE MAILLE ┆           ┆           ┆   ┆           ┆ ouvrages… ┆ ouvrages… ┆ de génie │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 298600602 ┆ ASS       ┆ 4299Z     ┆ NN        ┆ … ┆ null      ┆ Construct ┆ Construct ┆ Constr.  │
│ 00015     ┆ FONCIERE  ┆           ┆           ┆   ┆           ┆ ion       ┆ ion       ┆ aut.     │
│           ┆ DE REMEMB ┆           ┆           ┆   ┆           ┆ d'autres  ┆ d'autres  ┆ ouvrage  │
│           ┆ REMENT D… ┆           ┆           ┆   ┆           ┆ ouvrages… ┆ ouvrages… ┆ de génie │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 298600644 ┆ ASS       ┆ 4299Z     ┆ NN        ┆ … ┆ null      ┆ Construct ┆ Construct ┆ Constr.  │
│ 00017     ┆ FONCIERE  ┆           ┆           ┆   ┆           ┆ ion       ┆ ion       ┆ aut.     │
│           ┆ DE REMEMB ┆           ┆           ┆   ┆           ┆ d'autres  ┆ d'autres  ┆ ouvrage  │
│           ┆ DE MAZE…  ┆           ┆           ┆   ┆           ┆ ouvrages… ┆ ouvrages… ┆ de génie │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 298600834 ┆ ASSOCIATI ┆ 4299Z     ┆ NN        ┆ … ┆ 6673572.1 ┆ Construct ┆ Construct ┆ Constr.  │
│ 00014     ┆ ON        ┆           ┆           ┆   ┆ 07521303  ┆ ion       ┆ ion       ┆ aut.     │
│           ┆ FONCIERE  ┆           ┆           ┆   ┆           ┆ d'autres  ┆ d'autres  ┆ ouvrage  │
│           ┆ DE ROIFFE ┆           ┆           ┆   ┆           ┆ ouvrages… ┆ ouvrages… ┆ de génie │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 298600842 ┆ ASS       ┆ 4299Z     ┆ NN        ┆ … ┆ null      ┆ Construct ┆ Construct ┆ Constr.  │
│ 00017     ┆ FONCIERE  ┆           ┆           ┆   ┆           ┆ ion       ┆ ion       ┆ aut.     │
│           ┆ DE REMEMB ┆           ┆           ┆   ┆           ┆ d'autres  ┆ d'autres  ┆ ouvrage  │
│           ┆ REMENT D… ┆           ┆           ┆   ┆           ┆ ouvrages… ┆ ouvrages… ┆ de génie │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df["industry_description"].unique()

shape: (730,)
Series: 'industry_description' [str]
[
	"Activités des agences de trava…
	"Édition de livres"
	"Horlogerie"
	"Construction de routes et auto…
	"Activités d’ordre public et de…
	…
	"Commerce de détail d'enregistr…
	"Gestion des musées"
	"Réparation d'appareils électro…
	"Commerce de gros (commerce int…
	"Vente à distance sur catalogue…
]

In [ ]:
code_postaux = pl.read_csv(
    "./DATA/base-officielle-des-codes-postaux.csv",
    separator=";",
    truncate_ragged_lines=True,
    ignore_errors=True,
    null_values=["2A001", "[ND]", "NA", ""]
)

In [ ]:
code_postaux.head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬────────────┬─────────┬────────────┬───────────┬───────────┐
│ Code_commu ┆ Nom_de_la_ ┆ Code_posta ┆ Libellé_d_ ┆ Ligne_5 ┆ Departemen ┆ geom      ┆ centroid  │
│ ne_INSEE   ┆ commune    ┆ l          ┆ achemineme ┆ ---     ┆ t          ┆ ---       ┆ ---       │
│ ---        ┆ ---        ┆ ---        ┆ nt         ┆ str     ┆ ---        ┆ str       ┆ str       │
│ i64        ┆ str        ┆ i64        ┆ ---        ┆         ┆ i64        ┆           ┆           │
│            ┆            ┆            ┆ str        ┆         ┆            ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═════════╪════════════╪═══════════╪═══════════╡
│ 75104      ┆ PARIS 04   ┆ 75004      ┆ PARIS      ┆ null    ┆ 75         ┆ {"coordin ┆ 48.854350 │
│            ┆            ┆            ┆            ┆         ┆            ┆ ates":    ┆ 603, 2.35 │
│            ┆            ┆            ┆            ┆         ┆            ┆ [[[[2.368 ┆ 7625608   │
│            ┆            ┆            ┆            ┆         ┆            ┆ 49088…    ┆           │
│ 75110      ┆ PARIS 10   ┆ 75010      ┆ PARIS      ┆ null    ┆ 75         ┆ {"coordin ┆ 48.876129 │
│            ┆            ┆            ┆            ┆         ┆            ┆ ates":    ┆ 334, 2.36 │
│            ┆            ┆            ┆            ┆         ┆            ┆ [[[[2.364 ┆ 0715102   │
│            ┆            ┆            ┆            ┆         ┆            ┆ 71357…    ┆           │
│ 77051      ┆ BRAY SUR   ┆ 77480      ┆ BRAY SUR   ┆ null    ┆ 77         ┆ {"coordin ┆ 48.414017 │
│            ┆ SEINE      ┆            ┆ SEINE      ┆         ┆            ┆ ates":    ┆ 188, 3.24 │
│            ┆            ┆            ┆            ┆         ┆            ┆ [[[[3.262 ┆ 2863551   │
│            ┆            ┆            ┆            ┆         ┆            ┆ 29068…    ┆           │
│ 77052      ┆ BREAU      ┆ 77720      ┆ BREAU      ┆ null    ┆ 77         ┆ {"coordin ┆ 48.557440 │
│            ┆            ┆            ┆            ┆         ┆            ┆ ates":    ┆ 136, 2.87 │
│            ┆            ┆            ┆            ┆         ┆            ┆ [[[[2.890 ┆ 8536628   │
│            ┆            ┆            ┆            ┆         ┆            ┆ 54255…    ┆           │
│ 77055      ┆ BROU SUR   ┆ 77177      ┆ BROU SUR   ┆ null    ┆ 77         ┆ {"coordin ┆ 48.890767 │
│            ┆ CHANTEREIN ┆            ┆ CHANTEREIN ┆         ┆            ┆ ates":    ┆ 137, 2.63 │
│            ┆ E          ┆            ┆ E          ┆         ┆            ┆ [[[[2.657 ┆ 9890249   │
│            ┆            ┆            ┆            ┆         ┆            ┆ 45618…    ┆           │
└────────────┴────────────┴────────────┴────────────┴─────────┴────────────┴───────────┴───────────┘

In [ ]:
code_postaux.columns

['Code_commune_INSEE',
 'Nom_de_la_commune',
 'Code_postal',
 'Libellé_d_acheminement',
 'Ligne_5',
 'Departement',
 'geom',
 'centroid']

In [ ]:
code_postaux["Code_postal"].value_counts().sort("count", descending=True).head(10)

shape: (10, 2)
┌─────────────┬───────┐
│ Code_postal ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 77320       ┆ 24    │
│ 77760       ┆ 16    │
│ 91150       ┆ 15    │
│ 95450       ┆ 15    │
│ 78270       ┆ 14    │
│ 77410       ┆ 14    │
│ 95420       ┆ 14    │
│ 77440       ┆ 13    │
│ 77560       ┆ 13    │
│ 77230       ┆ 13    │
└─────────────┴───────┘